export const projects = [
  {
    id: '01',
    imgSrc: 'https://i.postimg.cc/gJ8xwHqv/Homeigo-final.png',
    title: 'Homeigo realtor website',
    description: 'For our final project, we collaborated on creating a realtor homepage. Working as a team of three, we undertook the entire project – constructing the database, managing all the functionality, crafting the user interface and design. Our toolkit encompassed a variety of technologies, such as React, Redux, Node.js, and MongoDB. A notable highlight was our integration of a user-friendly map feature along with a search function, elevating the overall user experience.',
    techs: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Redux', 'Express.js', 'Node.js', 'MongoDB', 'Styled Components', 'Mob-Programming'],
    githubLink: 'https://github.com/JohLeo/final-project',
    netlifyLink: 'https://melodic-daffodil-115469.netlify.app'
  },
  {
    id: '02',
    imgSrc: 'https://i.postimg.cc/sDyhhqL1/Auth-16.png',
    title: 'Authenticator',
    description: 'A pair programming project focused on developing an authenticator system. Our main objectives were to implement secure token-based authentication and ensure the safe storage of user passwords within the database. With an emphasis on security and defensive design, our goal was to create an authenticator solution that prioritizes safety and reliability.',
    techs: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Redux', 'Express.js', 'Node.js', 'Styled Components'],
    githubLink: 'https://github.com/JohLeo/project-auth',
    netlifyLink: 'https://effortless-empanada-ad1e86.netlify.app/'
  },
  {
    id: '03',
    imgSrc: 'https://i.postimg.cc/YS4G7HvD/Happy2-v15.png',
    title: 'Happy thoughts',
    description: ['A Twitter-like message app but with more positivity and less Elon Musk. I developed both the backend and frontend, building an API that enables users to fetch and post data to and from the database. This functionality allows you to share happy thoughts on the feed. Utilizing MongoDB on the backend allowed me to delve deeper into setting up endpoints, storing data, and managing user input.'],
    techs: ['HTML5', 'CSS3', 'JavaScript', 'React', 'MongoDB', 'Node.js', 'Express.js'],
    githubLink: 'https://github.com/JohLeo/project-happy-thoughts-api',
    netlifyLink: 'https://happy-mongo-api-jl.netlify.app'
  },
  {
    id: '05',
    imgSrc: 'https://i.postimg.cc/GtRHvTq6/Labyrinth-v12.png',
    title: 'The Labyrinth',
    description: 'We developed a text-based adventure game that allows users to navigate through a maze generated by a backend constructed using React and Redux, alongside a game API from Technigo. Our main focus was on leveraging thunks and Redux to ensure smooth communication with the backend. To add an extra layer of enjoyment, we designed our own images and settings for the project. ',
    techs: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Redux', 'Styled Components', 'Mob-Programming', 'Restful-API'],
    githubLink: 'https://github.com/Nahnahke/project-labyrinth',
    netlifyLink: 'https://project-labyrinth-jhs.netlify.app'
  },
  {
    id: '06',
    imgSrc: 'https://i.postimg.cc/Wp74Q39b/Todo-v11.png',
    title: 'To do',
    description: 'A game made out of Ai lorem ipsum dores lirum A game made out of Ai lorem ipsum dores lirum A game made out of Ai lorem ipsum dores lirum',
    techs: ['Tech needed'],
    githubLink: 'https://github.com/JohLeo/project-todos',
    netlifyLink: 'https://thetodo-jl.netlify.app'
  },
  {
    id: '07',
    imgSrc: 'https://i.postimg.cc/c44JZSj7/Ux-Collab-v9.png',
    title: 'UX collaboration',
    description: 'A game made out of Ai lorem ipsum dores lirum A game made out of Ai lorem ipsum dores lirum A game made out of Ai lorem ipsum dores lirum',
    techs: ['Tech needed'],
    githubLink: 'https://github.com/JohLeo/project-design-handoff',
    netlifyLink: 'https://ux-handoff-poweryoga.netlify.app'
  },
  {
    id: '08',
    imgSrc: 'https://i.postimg.cc/yxTWj6Gx/Survey-v6.png',
    title: 'Relaxing survey',
    description: 'A game made out of Ai lorem ipsum dores lirum A game made out of Ai lorem ipsum dores lirum A game made out of Ai lorem ipsum dores lirum',
    techs: ['Tech needed'],
    githubLink: 'https://github.com/JohLeo/project-survey',
    netlifyLink: 'https://stress-less-survey.netlify.app'
  },
  {
    id: '09',
    imgSrc: 'https://i.postimg.cc/W4QDbHrN/Movies-v8.png',
    title: 'Movie Releases',
    description: 'A multi-page web application using React Router and an API from IMDB. It allows users to view a list of latest movie releases and select a movie to read more about. Built as a pair-programming project.',
    techs: ['HTML', 'CSS', 'JavaScript', 'React'],
    githubLink: 'https://github.com/mvfrid/project-movies',
    netlifyLink: 'https://johanna-matilda-project-movies.netlify.app'
  },
  {
    id: '10',
    imgSrc: 'https://i.postimg.cc/vHz6LXRh/Guess-Who-v2.png',
    title: 'Guess what? - game',
    description: 'A digital version of the old classic game {Guess-Who?}. Using array methods such as filter, forEach and mapping. The project set out to teach us to use JavaScript scope, objects and arrays.',
    techs: ['HTML', 'CSS', 'JavaScript'],
    githubLink: 'https://github.com/JohLeo/project-guess-who',
    netlifyLink: 'https://poetic-cobbler-eaa36b.netlify.app'
  },
  {
    id: '11',
    imgSrc: 'https://i.postimg.cc/jSSn8Ntb/Chatbot-v1.png',
    title: 'Chatbot',
    description: 'The first JavaScript project in Technigos frontend developer bootcamp. Created to understand the fundamentals of JS. Built by using variables, functions, control flow and conditional statements/ternary operators.',
    techs: ['HTML5', 'CSS3', 'JavaScript'],
    githubLink: 'https://github.com/JohLeo/project-chatbot',
    netlifyLink: 'https://flourishing-begonia-4f3673.netlify.app'
  },
  {
    id: '12',
    imgSrc: 'https://i.postimg.cc/9FY1wD55/maze-5.png',
    title: 'Weather app',
    description: 'Text needed and project is on Sallys Git A game made out of Ai lorem ipsum dores lirum A game made out of Ai lorem ipsum dores lirum A game made out of Ai lorem ipsum dores lirum',
    techs: ['Tech needed'],
    githubLink: 'https://github.com/sammyolsson/project-weather-app',
    netlifyLink: 'https://scintillating-tanuki-2a80a2.netlify.app'
  }
];